version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: nestJS-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
